// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_multiply_top_matrix_multiply_alt2_HH_
#define _matrix_multiply_top_matrix_multiply_alt2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp.h"
#include "matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp.h"
#include "matrix_multiply_top_matrix_multiply_alt2_sum_mult.h"

namespace ap_rtl {

struct matrix_multiply_top_matrix_multiply_alt2 : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > A_address0;
    sc_out< sc_logic > A_ce0;
    sc_in< sc_lv<32> > A_q0;
    sc_out< sc_lv<4> > B_address0;
    sc_out< sc_logic > B_ce0;
    sc_in< sc_lv<32> > B_q0;
    sc_out< sc_lv<4> > C_address0;
    sc_out< sc_logic > C_ce0;
    sc_out< sc_logic > C_we0;
    sc_out< sc_lv<32> > C_d0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    matrix_multiply_top_matrix_multiply_alt2(sc_module_name name);
    SC_HAS_PROCESS(matrix_multiply_top_matrix_multiply_alt2);

    ~matrix_multiply_top_matrix_multiply_alt2();

    sc_trace_file* mVcdFile;

    matrix_multiply_top_matrix_multiply_alt2_sum_mult* sum_mult_U;
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>* matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0;
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>* matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_20;
    sc_signal< sc_lv<5> > indvar_flatten1_reg_111;
    sc_signal< sc_lv<2> > Col_assign_2_reg_122;
    sc_signal< sc_lv<4> > indvar_flatten_reg_133;
    sc_signal< sc_lv<2> > Row_assign_reg_144;
    sc_signal< sc_lv<2> > Col_assign_reg_155;
    sc_signal< sc_lv<1> > exitcond_flatten1_fu_178_p2;
    sc_signal< sc_lv<1> > exitcond_flatten1_reg_400;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_1;
    sc_signal< bool > ap_sig_61;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it5;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it6;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it7;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it8;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it9;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it10;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it11;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter4;
    sc_signal< sc_lv<5> > indvar_flatten_next1_fu_184_p2;
    sc_signal< sc_lv<1> > tmp_mid2_fu_222_p3;
    sc_signal< sc_lv<1> > tmp_mid2_reg_409;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter5;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter6;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter7;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter8;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10;
    sc_signal< sc_lv<1> > tmp_mid2_14_fu_242_p3;
    sc_signal< sc_lv<1> > tmp_mid2_14_reg_413;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter2;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter3;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter4;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter5;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter6;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter7;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter8;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9;
    sc_signal< sc_lv<1> > ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10;
    sc_signal< sc_lv<2> > tmp_i_i_mid2_v_fu_250_p3;
    sc_signal< sc_lv<2> > tmp_i_i_mid2_v_reg_417;
    sc_signal< sc_lv<2> > Col_assign_mid2_fu_288_p3;
    sc_signal< sc_lv<2> > Col_assign_mid2_reg_424;
    sc_signal< sc_lv<2> > tmp_1_mid2_fu_296_p3;
    sc_signal< sc_lv<2> > tmp_1_mid2_reg_429;
    sc_signal< sc_lv<2> > c_fu_304_p2;
    sc_signal< sc_lv<4> > indvar_flatten_next_fu_316_p3;
    sc_signal< sc_lv<5> > tmp_17_fu_389_p2;
    sc_signal< sc_lv<5> > tmp_17_reg_456;
    sc_signal< sc_lv<5> > ap_reg_ppstg_tmp_17_reg_456_pp0_iter2;
    sc_signal< sc_lv<5> > ap_reg_ppstg_tmp_17_reg_456_pp0_iter3;
    sc_signal< sc_lv<5> > ap_reg_ppstg_tmp_17_reg_456_pp0_iter4;
    sc_signal< sc_lv<4> > C_addr_reg_471;
    sc_signal< sc_lv<4> > ap_reg_ppstg_C_addr_reg_471_pp0_iter6;
    sc_signal< sc_lv<4> > ap_reg_ppstg_C_addr_reg_471_pp0_iter7;
    sc_signal< sc_lv<4> > ap_reg_ppstg_C_addr_reg_471_pp0_iter8;
    sc_signal< sc_lv<4> > ap_reg_ppstg_C_addr_reg_471_pp0_iter9;
    sc_signal< sc_lv<4> > ap_reg_ppstg_C_addr_reg_471_pp0_iter10;
    sc_signal< sc_lv<4> > sum_mult_addr_reg_476;
    sc_signal< sc_lv<4> > ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter6;
    sc_signal< sc_lv<4> > ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter7;
    sc_signal< sc_lv<4> > ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter8;
    sc_signal< sc_lv<4> > ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter9;
    sc_signal< sc_lv<32> > grp_fu_172_p2;
    sc_signal< sc_lv<32> > mult_reg_482;
    sc_signal< sc_lv<32> > ap_reg_ppstg_mult_reg_482_pp0_iter6;
    sc_signal< sc_lv<32> > ap_reg_ppstg_mult_reg_482_pp0_iter7;
    sc_signal< sc_lv<32> > ap_reg_ppstg_mult_reg_482_pp0_iter8;
    sc_signal< sc_lv<32> > ap_reg_ppstg_mult_reg_482_pp0_iter9;
    sc_signal< sc_lv<32> > sum_mult_q0;
    sc_signal< sc_lv<32> > grp_fu_166_p2;
    sc_signal< sc_lv<32> > tmp_4_reg_493;
    sc_signal< sc_lv<4> > sum_mult_address0;
    sc_signal< sc_logic > sum_mult_ce0;
    sc_signal< sc_logic > sum_mult_ce1;
    sc_signal< sc_logic > sum_mult_we1;
    sc_signal< sc_lv<32> > sum_mult_d1;
    sc_signal< sc_lv<2> > Col_assign_2_phi_fu_126_p4;
    sc_signal< sc_lv<2> > Row_assign_phi_fu_148_p4;
    sc_signal< sc_lv<64> > tmp_22_cast_fu_370_p1;
    sc_signal< sc_lv<64> > tmp_23_cast_fu_384_p1;
    sc_signal< sc_lv<64> > tmp_24_cast_fu_395_p1;
    sc_signal< sc_lv<1> > exitcond_flatten_fu_196_p2;
    sc_signal< sc_lv<2> > k_fu_190_p2;
    sc_signal< sc_lv<1> > tmp_mid1_fu_210_p2;
    sc_signal< sc_lv<1> > tmp3_fu_216_p2;
    sc_signal< sc_lv<1> > tmp_mid1_13_fu_230_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_236_p2;
    sc_signal< sc_lv<1> > exitcond_fu_264_p2;
    sc_signal< sc_lv<1> > not_exitcond_flatten_fu_258_p2;
    sc_signal< sc_lv<2> > Row_assign_mid_fu_202_p3;
    sc_signal< sc_lv<1> > exitcond_mid_fu_270_p2;
    sc_signal< sc_lv<1> > tmp_13_fu_282_p2;
    sc_signal< sc_lv<2> > r_fu_276_p2;
    sc_signal< sc_lv<4> > indvar_flatten_op_fu_310_p2;
    sc_signal< sc_lv<4> > tmp_s_fu_327_p3;
    sc_signal< sc_lv<5> > p_shl1_cast_fu_334_p1;
    sc_signal< sc_lv<5> > tmp_i_i_mid2_cast_fu_324_p1;
    sc_signal< sc_lv<4> > tmp_fu_347_p3;
    sc_signal< sc_lv<5> > p_shl_cast_fu_354_p1;
    sc_signal< sc_lv<5> > tmp_1_mid2_cast_fu_344_p1;
    sc_signal< sc_lv<5> > tmp_14_fu_358_p2;
    sc_signal< sc_lv<5> > tmp_15_fu_364_p2;
    sc_signal< sc_lv<5> > tmp_i_i4_cast_fu_375_p1;
    sc_signal< sc_lv<5> > tmp_12_fu_338_p2;
    sc_signal< sc_lv<5> > tmp_16_fu_378_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_2;
    sc_signal< bool > ap_sig_395;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_sig_229;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_st1_fsm_0;
    static const sc_lv<3> ap_ST_pp0_stg0_fsm_1;
    static const sc_lv<3> ap_ST_st14_fsm_2;
    static const bool ap_true;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<5> ap_const_lv5_1B;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_A_address0();
    void thread_A_ce0();
    void thread_B_address0();
    void thread_B_ce0();
    void thread_C_address0();
    void thread_C_ce0();
    void thread_C_d0();
    void thread_C_we0();
    void thread_Col_assign_2_phi_fu_126_p4();
    void thread_Col_assign_mid2_fu_288_p3();
    void thread_Row_assign_mid_fu_202_p3();
    void thread_Row_assign_phi_fu_148_p4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_20();
    void thread_ap_sig_229();
    void thread_ap_sig_395();
    void thread_ap_sig_61();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_1();
    void thread_ap_sig_cseq_ST_st14_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_c_fu_304_p2();
    void thread_exitcond_flatten1_fu_178_p2();
    void thread_exitcond_flatten_fu_196_p2();
    void thread_exitcond_fu_264_p2();
    void thread_exitcond_mid_fu_270_p2();
    void thread_indvar_flatten_next1_fu_184_p2();
    void thread_indvar_flatten_next_fu_316_p3();
    void thread_indvar_flatten_op_fu_310_p2();
    void thread_k_fu_190_p2();
    void thread_not_exitcond_flatten_fu_258_p2();
    void thread_p_shl1_cast_fu_334_p1();
    void thread_p_shl_cast_fu_354_p1();
    void thread_r_fu_276_p2();
    void thread_sum_mult_address0();
    void thread_sum_mult_ce0();
    void thread_sum_mult_ce1();
    void thread_sum_mult_d1();
    void thread_sum_mult_we1();
    void thread_tmp3_fu_216_p2();
    void thread_tmp_12_fu_338_p2();
    void thread_tmp_13_fu_282_p2();
    void thread_tmp_14_fu_358_p2();
    void thread_tmp_15_fu_364_p2();
    void thread_tmp_16_fu_378_p2();
    void thread_tmp_17_fu_389_p2();
    void thread_tmp_1_mid2_cast_fu_344_p1();
    void thread_tmp_1_mid2_fu_296_p3();
    void thread_tmp_22_cast_fu_370_p1();
    void thread_tmp_23_cast_fu_384_p1();
    void thread_tmp_24_cast_fu_395_p1();
    void thread_tmp_2_fu_236_p2();
    void thread_tmp_fu_347_p3();
    void thread_tmp_i_i4_cast_fu_375_p1();
    void thread_tmp_i_i_mid2_cast_fu_324_p1();
    void thread_tmp_i_i_mid2_v_fu_250_p3();
    void thread_tmp_mid1_13_fu_230_p2();
    void thread_tmp_mid1_fu_210_p2();
    void thread_tmp_mid2_14_fu_242_p3();
    void thread_tmp_mid2_fu_222_p3();
    void thread_tmp_s_fu_327_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
