// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_multiply_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_multiply_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_multiply_top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> matrix_multiply_top::ap_ST_st1_fsm_0 = "1";
const sc_lv<11> matrix_multiply_top::ap_ST_st2_fsm_1 = "10";
const sc_lv<11> matrix_multiply_top::ap_ST_st3_fsm_2 = "100";
const sc_lv<11> matrix_multiply_top::ap_ST_st4_fsm_3 = "1000";
const sc_lv<11> matrix_multiply_top::ap_ST_st5_fsm_4 = "10000";
const sc_lv<11> matrix_multiply_top::ap_ST_st6_fsm_5 = "100000";
const sc_lv<11> matrix_multiply_top::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<11> matrix_multiply_top::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<11> matrix_multiply_top::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<11> matrix_multiply_top::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<11> matrix_multiply_top::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> matrix_multiply_top::ap_const_lv1_1 = "1";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_multiply_top::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_5 = "101";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_8 = "1000";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_9 = "1001";
const sc_lv<2> matrix_multiply_top::ap_const_lv2_0 = "00";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_6 = "110";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_7 = "111";
const sc_lv<32> matrix_multiply_top::ap_const_lv32_A = "1010";
const sc_lv<2> matrix_multiply_top::ap_const_lv2_3 = "11";
const sc_lv<2> matrix_multiply_top::ap_const_lv2_1 = "1";

matrix_multiply_top::matrix_multiply_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    a_i_U = new matrix_multiply_top_a_i("a_i_U");
    a_i_U->clk(ap_clk);
    a_i_U->reset(ap_rst);
    a_i_U->address0(a_i_address0);
    a_i_U->ce0(a_i_ce0);
    a_i_U->we0(a_i_we0);
    a_i_U->d0(A_q0);
    a_i_U->q0(a_i_q0);
    b_i_U = new matrix_multiply_top_a_i("b_i_U");
    b_i_U->clk(ap_clk);
    b_i_U->reset(ap_rst);
    b_i_U->address0(b_i_address0);
    b_i_U->ce0(b_i_ce0);
    b_i_U->we0(b_i_we0);
    b_i_U->d0(B_q0);
    b_i_U->q0(b_i_q0);
    C_assign_U = new matrix_multiply_top_a_i("C_assign_U");
    C_assign_U->clk(ap_clk);
    C_assign_U->reset(ap_rst);
    C_assign_U->address0(C_assign_address0);
    C_assign_U->ce0(C_assign_ce0);
    C_assign_U->we0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_we0);
    C_assign_U->d0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_d0);
    C_assign_U->q0(C_assign_q0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198 = new matrix_multiply_top_matrix_multiply_alt2("grp_matrix_multiply_top_matrix_multiply_alt2_fu_198");
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_clk(ap_clk);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_rst(ap_rst);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_start(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_done(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_idle(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_idle);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->ap_ready(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_ready);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->A_address0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->A_ce0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->A_q0(a_i_q0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->B_address0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->B_ce0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->B_q0(b_i_q0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->C_address0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->C_ce0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->C_we0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_we0);
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198->C_d0(grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_12_cast_fu_260_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_15_cast_fu_320_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_C_address0);
    sensitive << ( tmp_16_cast_reg_468 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_C_assign_address0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_16_cast_fu_380_p1 );
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_C_assign_ce0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_C_d0);
    sensitive << ( C_assign_q0 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_a_i_address0);
    sensitive << ( tmp_12_cast_reg_406 );
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_a_i_ce0);
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_a_i_we0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( exitcond1_fu_325_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( exitcond1_fu_325_p2 );

    SC_METHOD(thread_ap_sig_104);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_134);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_202);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_217);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_226);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_240);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_59);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_90);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_240 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_26 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_59 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_202 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_90 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_104 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_217 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_226 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_120 );

    SC_METHOD(thread_b_i_address0);
    sensitive << ( tmp_15_cast_reg_437 );
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_b_i_ce0);
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_b_i_we0);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_c_1_fu_245_p2);
    sensitive << ( c_reg_143 );

    SC_METHOD(thread_c_2_fu_305_p2);
    sensitive << ( c2_reg_165 );

    SC_METHOD(thread_c_3_fu_365_p2);
    sensitive << ( c4_reg_187 );

    SC_METHOD(thread_exitcond1_fu_325_p2);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( r3_reg_176 );

    SC_METHOD(thread_exitcond2_fu_299_p2);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( c2_reg_165 );

    SC_METHOD(thread_exitcond3_fu_265_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( r1_reg_154 );

    SC_METHOD(thread_exitcond4_fu_239_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( c_reg_143 );

    SC_METHOD(thread_exitcond5_fu_205_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( r_reg_132 );

    SC_METHOD(thread_exitcond_fu_359_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( c4_reg_187 );

    SC_METHOD(thread_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start);
    sensitive << ( ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start );

    SC_METHOD(thread_p_shl1_cast_fu_289_p1);
    sensitive << ( tmp_s_fu_281_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_349_p1);
    sensitive << ( tmp_5_fu_341_p3 );

    SC_METHOD(thread_p_shl_cast_fu_229_p1);
    sensitive << ( tmp_6_fu_221_p3 );

    SC_METHOD(thread_r_1_fu_211_p2);
    sensitive << ( r_reg_132 );

    SC_METHOD(thread_r_2_fu_271_p2);
    sensitive << ( r1_reg_154 );

    SC_METHOD(thread_r_3_fu_331_p2);
    sensitive << ( r3_reg_176 );

    SC_METHOD(thread_tmp_10_fu_315_p2);
    sensitive << ( tmp_1_reg_424 );
    sensitive << ( tmp_7_cast_fu_311_p1 );

    SC_METHOD(thread_tmp_11_fu_375_p2);
    sensitive << ( tmp_7_reg_455 );
    sensitive << ( tmp_cast_10_fu_371_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_260_p1);
    sensitive << ( tmp_3_fu_255_p2 );

    SC_METHOD(thread_tmp_15_cast_fu_320_p1);
    sensitive << ( tmp_10_fu_315_p2 );

    SC_METHOD(thread_tmp_16_cast_fu_380_p1);
    sensitive << ( tmp_11_fu_375_p2 );

    SC_METHOD(thread_tmp_1_cast_fu_277_p1);
    sensitive << ( r1_reg_154 );

    SC_METHOD(thread_tmp_1_fu_293_p2);
    sensitive << ( p_shl1_cast_fu_289_p1 );
    sensitive << ( tmp_1_cast_fu_277_p1 );

    SC_METHOD(thread_tmp_3_cast_fu_251_p1);
    sensitive << ( c_reg_143 );

    SC_METHOD(thread_tmp_3_fu_255_p2);
    sensitive << ( tmp_9_reg_393 );
    sensitive << ( tmp_3_cast_fu_251_p1 );

    SC_METHOD(thread_tmp_5_cast_fu_337_p1);
    sensitive << ( r3_reg_176 );

    SC_METHOD(thread_tmp_5_fu_341_p3);
    sensitive << ( r3_reg_176 );

    SC_METHOD(thread_tmp_6_fu_221_p3);
    sensitive << ( r_reg_132 );

    SC_METHOD(thread_tmp_7_cast_fu_311_p1);
    sensitive << ( c2_reg_165 );

    SC_METHOD(thread_tmp_7_fu_353_p2);
    sensitive << ( p_shl2_cast_fu_349_p1 );
    sensitive << ( tmp_5_cast_fu_337_p1 );

    SC_METHOD(thread_tmp_9_fu_233_p2);
    sensitive << ( p_shl_cast_fu_229_p1 );
    sensitive << ( tmp_cast_fu_217_p1 );

    SC_METHOD(thread_tmp_cast_10_fu_371_p1);
    sensitive << ( c4_reg_187 );

    SC_METHOD(thread_tmp_cast_fu_217_p1);
    sensitive << ( r_reg_132 );

    SC_METHOD(thread_tmp_s_fu_281_p3);
    sensitive << ( r1_reg_154 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond5_fu_205_p2 );
    sensitive << ( exitcond4_fu_239_p2 );
    sensitive << ( exitcond3_fu_265_p2 );
    sensitive << ( exitcond2_fu_299_p2 );
    sensitive << ( exitcond1_fu_325_p2 );
    sensitive << ( exitcond_fu_359_p2 );
    sensitive << ( grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000001";
    ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_multiply_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_26, "ap_sig_26");
    sc_trace(mVcdFile, r_1_fu_211_p2, "r_1_fu_211_p2");
    sc_trace(mVcdFile, r_1_reg_388, "r_1_reg_388");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_59, "ap_sig_59");
    sc_trace(mVcdFile, tmp_9_fu_233_p2, "tmp_9_fu_233_p2");
    sc_trace(mVcdFile, tmp_9_reg_393, "tmp_9_reg_393");
    sc_trace(mVcdFile, exitcond5_fu_205_p2, "exitcond5_fu_205_p2");
    sc_trace(mVcdFile, c_1_fu_245_p2, "c_1_fu_245_p2");
    sc_trace(mVcdFile, c_1_reg_401, "c_1_reg_401");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, tmp_12_cast_fu_260_p1, "tmp_12_cast_fu_260_p1");
    sc_trace(mVcdFile, tmp_12_cast_reg_406, "tmp_12_cast_reg_406");
    sc_trace(mVcdFile, exitcond4_fu_239_p2, "exitcond4_fu_239_p2");
    sc_trace(mVcdFile, r_2_fu_271_p2, "r_2_fu_271_p2");
    sc_trace(mVcdFile, r_2_reg_419, "r_2_reg_419");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_90, "ap_sig_90");
    sc_trace(mVcdFile, tmp_1_fu_293_p2, "tmp_1_fu_293_p2");
    sc_trace(mVcdFile, tmp_1_reg_424, "tmp_1_reg_424");
    sc_trace(mVcdFile, exitcond3_fu_265_p2, "exitcond3_fu_265_p2");
    sc_trace(mVcdFile, c_2_fu_305_p2, "c_2_fu_305_p2");
    sc_trace(mVcdFile, c_2_reg_432, "c_2_reg_432");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_104, "ap_sig_104");
    sc_trace(mVcdFile, tmp_15_cast_fu_320_p1, "tmp_15_cast_fu_320_p1");
    sc_trace(mVcdFile, tmp_15_cast_reg_437, "tmp_15_cast_reg_437");
    sc_trace(mVcdFile, exitcond2_fu_299_p2, "exitcond2_fu_299_p2");
    sc_trace(mVcdFile, r_3_fu_331_p2, "r_3_fu_331_p2");
    sc_trace(mVcdFile, r_3_reg_450, "r_3_reg_450");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_120, "ap_sig_120");
    sc_trace(mVcdFile, tmp_7_fu_353_p2, "tmp_7_fu_353_p2");
    sc_trace(mVcdFile, tmp_7_reg_455, "tmp_7_reg_455");
    sc_trace(mVcdFile, exitcond1_fu_325_p2, "exitcond1_fu_325_p2");
    sc_trace(mVcdFile, c_3_fu_365_p2, "c_3_fu_365_p2");
    sc_trace(mVcdFile, c_3_reg_463, "c_3_reg_463");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_134, "ap_sig_134");
    sc_trace(mVcdFile, tmp_16_cast_fu_380_p1, "tmp_16_cast_fu_380_p1");
    sc_trace(mVcdFile, tmp_16_cast_reg_468, "tmp_16_cast_reg_468");
    sc_trace(mVcdFile, exitcond_fu_359_p2, "exitcond_fu_359_p2");
    sc_trace(mVcdFile, a_i_address0, "a_i_address0");
    sc_trace(mVcdFile, a_i_ce0, "a_i_ce0");
    sc_trace(mVcdFile, a_i_we0, "a_i_we0");
    sc_trace(mVcdFile, a_i_q0, "a_i_q0");
    sc_trace(mVcdFile, b_i_address0, "b_i_address0");
    sc_trace(mVcdFile, b_i_ce0, "b_i_ce0");
    sc_trace(mVcdFile, b_i_we0, "b_i_we0");
    sc_trace(mVcdFile, b_i_q0, "b_i_q0");
    sc_trace(mVcdFile, C_assign_address0, "C_assign_address0");
    sc_trace(mVcdFile, C_assign_ce0, "C_assign_ce0");
    sc_trace(mVcdFile, C_assign_q0, "C_assign_q0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_idle, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_idle");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_ready, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_ready");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_we0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_we0");
    sc_trace(mVcdFile, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_d0, "grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_d0");
    sc_trace(mVcdFile, r_reg_132, "r_reg_132");
    sc_trace(mVcdFile, c_reg_143, "c_reg_143");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_202, "ap_sig_202");
    sc_trace(mVcdFile, r1_reg_154, "r1_reg_154");
    sc_trace(mVcdFile, c2_reg_165, "c2_reg_165");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_217, "ap_sig_217");
    sc_trace(mVcdFile, r3_reg_176, "r3_reg_176");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_226, "ap_sig_226");
    sc_trace(mVcdFile, c4_reg_187, "c4_reg_187");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_240, "ap_sig_240");
    sc_trace(mVcdFile, ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start, "ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start");
    sc_trace(mVcdFile, tmp_6_fu_221_p3, "tmp_6_fu_221_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_229_p1, "p_shl_cast_fu_229_p1");
    sc_trace(mVcdFile, tmp_cast_fu_217_p1, "tmp_cast_fu_217_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_251_p1, "tmp_3_cast_fu_251_p1");
    sc_trace(mVcdFile, tmp_3_fu_255_p2, "tmp_3_fu_255_p2");
    sc_trace(mVcdFile, tmp_s_fu_281_p3, "tmp_s_fu_281_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_289_p1, "p_shl1_cast_fu_289_p1");
    sc_trace(mVcdFile, tmp_1_cast_fu_277_p1, "tmp_1_cast_fu_277_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_311_p1, "tmp_7_cast_fu_311_p1");
    sc_trace(mVcdFile, tmp_10_fu_315_p2, "tmp_10_fu_315_p2");
    sc_trace(mVcdFile, tmp_5_fu_341_p3, "tmp_5_fu_341_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_349_p1, "p_shl2_cast_fu_349_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_337_p1, "tmp_5_cast_fu_337_p1");
    sc_trace(mVcdFile, tmp_cast_10_fu_371_p1, "tmp_cast_10_fu_371_p1");
    sc_trace(mVcdFile, tmp_11_fu_375_p2, "tmp_11_fu_375_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_multiply_top.hdltvin.dat");
    mHdltvoutHandle.open("matrix_multiply_top.hdltvout.dat");
}

matrix_multiply_top::~matrix_multiply_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete a_i_U;
    delete b_i_U;
    delete C_assign_U;
    delete grp_matrix_multiply_top_matrix_multiply_alt2_fu_198;
}

void matrix_multiply_top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_265_p2.read()))) {
            ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_ready.read())) {
            ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        c2_reg_165 = c_2_reg_432.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_265_p2.read()))) {
        c2_reg_165 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        c4_reg_187 = c_3_reg_463.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_325_p2.read()))) {
        c4_reg_187 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        c_reg_143 = c_1_reg_401.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond5_fu_205_p2.read(), ap_const_lv1_0))) {
        c_reg_143 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond5_fu_205_p2.read(), ap_const_lv1_0))) {
        r1_reg_154 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_299_p2.read()))) {
        r1_reg_154 = r_2_reg_419.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_359_p2.read()))) {
        r3_reg_176 = r_3_reg_450.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done.read()))) {
        r3_reg_176 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_239_p2.read()))) {
        r_reg_132 = r_1_reg_388.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        r_reg_132 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        c_1_reg_401 = c_1_fu_245_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        c_2_reg_432 = c_2_fu_305_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        c_3_reg_463 = c_3_fu_365_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        r_1_reg_388 = r_1_fu_211_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        r_2_reg_419 = r_2_fu_271_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        r_3_reg_450 = r_3_fu_331_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_239_p2.read()))) {
        tmp_12_cast_reg_406 = tmp_12_cast_fu_260_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_299_p2.read()))) {
        tmp_15_cast_reg_437 = tmp_15_cast_fu_320_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_359_p2.read()))) {
        tmp_16_cast_reg_468 = tmp_16_cast_fu_380_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_265_p2.read()))) {
        tmp_1_reg_424 = tmp_1_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_325_p2.read()))) {
        tmp_7_reg_455 = tmp_7_fu_353_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond5_fu_205_p2.read(), ap_const_lv1_0))) {
        tmp_9_reg_393 = tmp_9_fu_233_p2.read();
    }
}

void matrix_multiply_top::thread_A_address0() {
    A_address0 =  (sc_lv<4>) (tmp_12_cast_fu_260_p1.read());
}

void matrix_multiply_top::thread_A_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_B_address0() {
    B_address0 =  (sc_lv<4>) (tmp_15_cast_fu_320_p1.read());
}

void matrix_multiply_top::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_C_address0() {
    C_address0 =  (sc_lv<4>) (tmp_16_cast_reg_468.read());
}

void matrix_multiply_top::thread_C_assign_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        C_assign_address0 =  (sc_lv<4>) (tmp_16_cast_fu_380_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        C_assign_address0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0.read();
    } else {
        C_assign_address0 = "XXXX";
    }
}

void matrix_multiply_top::thread_C_assign_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        C_assign_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        C_assign_ce0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0.read();
    } else {
        C_assign_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_C_d0() {
    C_d0 = C_assign_q0.read();
}

void matrix_multiply_top::thread_C_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_a_i_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        a_i_address0 =  (sc_lv<4>) (tmp_12_cast_reg_406.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        a_i_address0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0.read();
    } else {
        a_i_address0 = "XXXX";
    }
}

void matrix_multiply_top::thread_a_i_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        a_i_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        a_i_ce0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0.read();
    } else {
        a_i_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_a_i_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()))) {
        a_i_we0 = ap_const_logic_1;
    } else {
        a_i_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_325_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_325_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_104() {
    ap_sig_104 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void matrix_multiply_top::thread_ap_sig_120() {
    ap_sig_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void matrix_multiply_top::thread_ap_sig_134() {
    ap_sig_134 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void matrix_multiply_top::thread_ap_sig_202() {
    ap_sig_202 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void matrix_multiply_top::thread_ap_sig_217() {
    ap_sig_217 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void matrix_multiply_top::thread_ap_sig_226() {
    ap_sig_226 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void matrix_multiply_top::thread_ap_sig_240() {
    ap_sig_240 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void matrix_multiply_top::thread_ap_sig_26() {
    ap_sig_26 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void matrix_multiply_top::thread_ap_sig_59() {
    ap_sig_59 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void matrix_multiply_top::thread_ap_sig_74() {
    ap_sig_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void matrix_multiply_top::thread_ap_sig_90() {
    ap_sig_90 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_134.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_240.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_26.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_59.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_74.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_202.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_90.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_104.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_217.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_226.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_120.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_b_i_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        b_i_address0 =  (sc_lv<4>) (tmp_15_cast_reg_437.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        b_i_address0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0.read();
    } else {
        b_i_address0 = "XXXX";
    }
}

void matrix_multiply_top::thread_b_i_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        b_i_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        b_i_ce0 = grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0.read();
    } else {
        b_i_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_b_i_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        b_i_we0 = ap_const_logic_1;
    } else {
        b_i_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_top::thread_c_1_fu_245_p2() {
    c_1_fu_245_p2 = (!c_reg_143.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_reg_143.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_c_2_fu_305_p2() {
    c_2_fu_305_p2 = (!c2_reg_165.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c2_reg_165.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_c_3_fu_365_p2() {
    c_3_fu_365_p2 = (!c4_reg_187.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c4_reg_187.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_exitcond1_fu_325_p2() {
    exitcond1_fu_325_p2 = (!r3_reg_176.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r3_reg_176.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_exitcond2_fu_299_p2() {
    exitcond2_fu_299_p2 = (!c2_reg_165.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c2_reg_165.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_exitcond3_fu_265_p2() {
    exitcond3_fu_265_p2 = (!r1_reg_154.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r1_reg_154.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_exitcond4_fu_239_p2() {
    exitcond4_fu_239_p2 = (!c_reg_143.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_143.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_exitcond5_fu_205_p2() {
    exitcond5_fu_205_p2 = (!r_reg_132.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_reg_132.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_exitcond_fu_359_p2() {
    exitcond_fu_359_p2 = (!c4_reg_187.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c4_reg_187.read() == ap_const_lv2_3);
}

void matrix_multiply_top::thread_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start() {
    grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start = ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start.read();
}

void matrix_multiply_top::thread_p_shl1_cast_fu_289_p1() {
    p_shl1_cast_fu_289_p1 = esl_zext<5,4>(tmp_s_fu_281_p3.read());
}

void matrix_multiply_top::thread_p_shl2_cast_fu_349_p1() {
    p_shl2_cast_fu_349_p1 = esl_zext<5,4>(tmp_5_fu_341_p3.read());
}

void matrix_multiply_top::thread_p_shl_cast_fu_229_p1() {
    p_shl_cast_fu_229_p1 = esl_zext<5,4>(tmp_6_fu_221_p3.read());
}

void matrix_multiply_top::thread_r_1_fu_211_p2() {
    r_1_fu_211_p2 = (!r_reg_132.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_reg_132.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_r_2_fu_271_p2() {
    r_2_fu_271_p2 = (!r1_reg_154.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r1_reg_154.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_r_3_fu_331_p2() {
    r_3_fu_331_p2 = (!r3_reg_176.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r3_reg_176.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top::thread_tmp_10_fu_315_p2() {
    tmp_10_fu_315_p2 = (!tmp_1_reg_424.read().is_01() || !tmp_7_cast_fu_311_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_1_reg_424.read()) + sc_biguint<5>(tmp_7_cast_fu_311_p1.read()));
}

void matrix_multiply_top::thread_tmp_11_fu_375_p2() {
    tmp_11_fu_375_p2 = (!tmp_7_reg_455.read().is_01() || !tmp_cast_10_fu_371_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_7_reg_455.read()) + sc_biguint<5>(tmp_cast_10_fu_371_p1.read()));
}

void matrix_multiply_top::thread_tmp_12_cast_fu_260_p1() {
    tmp_12_cast_fu_260_p1 = esl_sext<64,5>(tmp_3_fu_255_p2.read());
}

void matrix_multiply_top::thread_tmp_15_cast_fu_320_p1() {
    tmp_15_cast_fu_320_p1 = esl_sext<64,5>(tmp_10_fu_315_p2.read());
}

void matrix_multiply_top::thread_tmp_16_cast_fu_380_p1() {
    tmp_16_cast_fu_380_p1 = esl_sext<64,5>(tmp_11_fu_375_p2.read());
}

void matrix_multiply_top::thread_tmp_1_cast_fu_277_p1() {
    tmp_1_cast_fu_277_p1 = esl_zext<5,2>(r1_reg_154.read());
}

void matrix_multiply_top::thread_tmp_1_fu_293_p2() {
    tmp_1_fu_293_p2 = (!p_shl1_cast_fu_289_p1.read().is_01() || !tmp_1_cast_fu_277_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl1_cast_fu_289_p1.read()) - sc_biguint<5>(tmp_1_cast_fu_277_p1.read()));
}

void matrix_multiply_top::thread_tmp_3_cast_fu_251_p1() {
    tmp_3_cast_fu_251_p1 = esl_zext<5,2>(c_reg_143.read());
}

void matrix_multiply_top::thread_tmp_3_fu_255_p2() {
    tmp_3_fu_255_p2 = (!tmp_9_reg_393.read().is_01() || !tmp_3_cast_fu_251_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_9_reg_393.read()) + sc_biguint<5>(tmp_3_cast_fu_251_p1.read()));
}

void matrix_multiply_top::thread_tmp_5_cast_fu_337_p1() {
    tmp_5_cast_fu_337_p1 = esl_zext<5,2>(r3_reg_176.read());
}

void matrix_multiply_top::thread_tmp_5_fu_341_p3() {
    tmp_5_fu_341_p3 = esl_concat<2,2>(r3_reg_176.read(), ap_const_lv2_0);
}

void matrix_multiply_top::thread_tmp_6_fu_221_p3() {
    tmp_6_fu_221_p3 = esl_concat<2,2>(r_reg_132.read(), ap_const_lv2_0);
}

void matrix_multiply_top::thread_tmp_7_cast_fu_311_p1() {
    tmp_7_cast_fu_311_p1 = esl_zext<5,2>(c2_reg_165.read());
}

void matrix_multiply_top::thread_tmp_7_fu_353_p2() {
    tmp_7_fu_353_p2 = (!p_shl2_cast_fu_349_p1.read().is_01() || !tmp_5_cast_fu_337_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl2_cast_fu_349_p1.read()) - sc_biguint<5>(tmp_5_cast_fu_337_p1.read()));
}

void matrix_multiply_top::thread_tmp_9_fu_233_p2() {
    tmp_9_fu_233_p2 = (!p_shl_cast_fu_229_p1.read().is_01() || !tmp_cast_fu_217_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl_cast_fu_229_p1.read()) - sc_biguint<5>(tmp_cast_fu_217_p1.read()));
}

void matrix_multiply_top::thread_tmp_cast_10_fu_371_p1() {
    tmp_cast_10_fu_371_p1 = esl_zext<5,2>(c4_reg_187.read());
}

void matrix_multiply_top::thread_tmp_cast_fu_217_p1() {
    tmp_cast_fu_217_p1 = esl_zext<5,2>(r_reg_132.read());
}

void matrix_multiply_top::thread_tmp_s_fu_281_p3() {
    tmp_s_fu_281_p3 = esl_concat<2,2>(r1_reg_154.read(), ap_const_lv2_0);
}

void matrix_multiply_top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond5_fu_205_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_239_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_265_p2.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_299_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done.read())) {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 256 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_325_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_359_p2.read())) {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

void matrix_multiply_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_address0\" :  \"" << B_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_ce0\" :  \"" << B_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_q0\" :  \"" << B_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_address0\" :  \"" << C_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_ce0\" :  \"" << C_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_we0\" :  \"" << C_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"C_d0\" :  \"" << C_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

