// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_multiply_top_matrix_multiply_alt2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_multiply_top_matrix_multiply_alt2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_multiply_top_matrix_multiply_alt2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> matrix_multiply_top_matrix_multiply_alt2::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> matrix_multiply_top_matrix_multiply_alt2::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> matrix_multiply_top_matrix_multiply_alt2::ap_ST_st14_fsm_2 = "100";
const bool matrix_multiply_top_matrix_multiply_alt2::ap_true = true;
const sc_lv<32> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv1_1 = "1";
const sc_lv<32> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv1_0 = "0";
const sc_lv<5> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv5_0 = "00000";
const sc_lv<2> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv2_0 = "00";
const sc_lv<4> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv4_0 = "0000";
const sc_lv<5> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv5_1B = "11011";
const sc_lv<5> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv5_1 = "1";
const sc_lv<2> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv2_1 = "1";
const sc_lv<4> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv4_9 = "1001";
const sc_lv<2> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv2_2 = "10";
const sc_lv<2> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv2_3 = "11";
const sc_lv<4> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv4_1 = "1";
const sc_lv<32> matrix_multiply_top_matrix_multiply_alt2::ap_const_lv32_2 = "10";

matrix_multiply_top_matrix_multiply_alt2::matrix_multiply_top_matrix_multiply_alt2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_mult_U = new matrix_multiply_top_matrix_multiply_alt2_sum_mult("sum_mult_U");
    sum_mult_U->clk(ap_clk);
    sum_mult_U->reset(ap_rst);
    sum_mult_U->address0(sum_mult_address0);
    sum_mult_U->ce0(sum_mult_ce0);
    sum_mult_U->q0(sum_mult_q0);
    sum_mult_U->address1(ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter9);
    sum_mult_U->ce1(sum_mult_ce1);
    sum_mult_U->we1(sum_mult_we1);
    sum_mult_U->d1(sum_mult_d1);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0 = new matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0");
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->clk(ap_clk);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->reset(ap_rst);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->din0(sum_mult_q0);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->din1(mult_reg_482);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->ce(ap_var_for_const0);
    matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0->dout(grp_fu_166_p2);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1 = new matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1");
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->clk(ap_clk);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->reset(ap_rst);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->din0(A_q0);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->din1(B_q0);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->ce(ap_var_for_const0);
    matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1->dout(grp_fu_172_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_22_cast_fu_370_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_23_cast_fu_384_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_C_addr_reg_471_pp0_iter10 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );

    SC_METHOD(thread_C_d0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( tmp_4_reg_493 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10 );

    SC_METHOD(thread_Col_assign_2_phi_fu_126_p4);
    sensitive << ( Col_assign_2_reg_122 );
    sensitive << ( exitcond_flatten1_reg_400 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_i_i_mid2_v_reg_417 );

    SC_METHOD(thread_Col_assign_mid2_fu_288_p3);
    sensitive << ( Col_assign_reg_155 );
    sensitive << ( tmp_13_fu_282_p2 );

    SC_METHOD(thread_Row_assign_mid_fu_202_p3);
    sensitive << ( Row_assign_phi_fu_148_p4 );
    sensitive << ( exitcond_flatten_fu_196_p2 );

    SC_METHOD(thread_Row_assign_phi_fu_148_p4);
    sensitive << ( Row_assign_reg_144 );
    sensitive << ( exitcond_flatten1_reg_400 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_1_mid2_reg_429 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_2 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_229);
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9 );

    SC_METHOD(thread_ap_sig_395);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_61 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_2);
    sensitive << ( ap_sig_395 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_c_fu_304_p2);
    sensitive << ( Col_assign_mid2_fu_288_p3 );

    SC_METHOD(thread_exitcond_flatten1_fu_178_p2);
    sensitive << ( indvar_flatten1_reg_111 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_flatten_fu_196_p2);
    sensitive << ( indvar_flatten_reg_133 );
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_fu_264_p2);
    sensitive << ( Col_assign_reg_155 );
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_mid_fu_270_p2);
    sensitive << ( exitcond_fu_264_p2 );
    sensitive << ( not_exitcond_flatten_fu_258_p2 );

    SC_METHOD(thread_indvar_flatten_next1_fu_184_p2);
    sensitive << ( indvar_flatten1_reg_111 );

    SC_METHOD(thread_indvar_flatten_next_fu_316_p3);
    sensitive << ( exitcond_flatten_fu_196_p2 );
    sensitive << ( indvar_flatten_op_fu_310_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_310_p2);
    sensitive << ( indvar_flatten_reg_133 );

    SC_METHOD(thread_k_fu_190_p2);
    sensitive << ( Col_assign_2_phi_fu_126_p4 );

    SC_METHOD(thread_not_exitcond_flatten_fu_258_p2);
    sensitive << ( exitcond_flatten_fu_196_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_334_p1);
    sensitive << ( tmp_s_fu_327_p3 );

    SC_METHOD(thread_p_shl_cast_fu_354_p1);
    sensitive << ( tmp_fu_347_p3 );

    SC_METHOD(thread_r_fu_276_p2);
    sensitive << ( Row_assign_mid_fu_202_p3 );

    SC_METHOD(thread_sum_mult_address0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( tmp_24_cast_fu_395_p1 );

    SC_METHOD(thread_sum_mult_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_sum_mult_ce1);
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9 );

    SC_METHOD(thread_sum_mult_d1);
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9 );
    sensitive << ( ap_reg_ppstg_mult_reg_482_pp0_iter9 );
    sensitive << ( grp_fu_166_p2 );
    sensitive << ( ap_sig_229 );

    SC_METHOD(thread_sum_mult_we1);
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9 );

    SC_METHOD(thread_tmp3_fu_216_p2);
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_2_phi_fu_126_p4 );

    SC_METHOD(thread_tmp_12_fu_338_p2);
    sensitive << ( p_shl1_cast_fu_334_p1 );
    sensitive << ( tmp_i_i_mid2_cast_fu_324_p1 );

    SC_METHOD(thread_tmp_13_fu_282_p2);
    sensitive << ( exitcond_flatten_fu_196_p2 );
    sensitive << ( exitcond_mid_fu_270_p2 );

    SC_METHOD(thread_tmp_14_fu_358_p2);
    sensitive << ( p_shl_cast_fu_354_p1 );
    sensitive << ( tmp_1_mid2_cast_fu_344_p1 );

    SC_METHOD(thread_tmp_15_fu_364_p2);
    sensitive << ( tmp_i_i_mid2_cast_fu_324_p1 );
    sensitive << ( tmp_14_fu_358_p2 );

    SC_METHOD(thread_tmp_16_fu_378_p2);
    sensitive << ( tmp_i_i4_cast_fu_375_p1 );
    sensitive << ( tmp_12_fu_338_p2 );

    SC_METHOD(thread_tmp_17_fu_389_p2);
    sensitive << ( tmp_14_fu_358_p2 );
    sensitive << ( tmp_i_i4_cast_fu_375_p1 );

    SC_METHOD(thread_tmp_1_mid2_cast_fu_344_p1);
    sensitive << ( tmp_1_mid2_reg_429 );

    SC_METHOD(thread_tmp_1_mid2_fu_296_p3);
    sensitive << ( Row_assign_mid_fu_202_p3 );
    sensitive << ( exitcond_mid_fu_270_p2 );
    sensitive << ( r_fu_276_p2 );

    SC_METHOD(thread_tmp_22_cast_fu_370_p1);
    sensitive << ( tmp_15_fu_364_p2 );

    SC_METHOD(thread_tmp_23_cast_fu_384_p1);
    sensitive << ( tmp_16_fu_378_p2 );

    SC_METHOD(thread_tmp_24_cast_fu_395_p1);
    sensitive << ( ap_reg_ppstg_tmp_17_reg_456_pp0_iter4 );

    SC_METHOD(thread_tmp_2_fu_236_p2);
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_2_phi_fu_126_p4 );

    SC_METHOD(thread_tmp_fu_347_p3);
    sensitive << ( tmp_1_mid2_reg_429 );

    SC_METHOD(thread_tmp_i_i4_cast_fu_375_p1);
    sensitive << ( Col_assign_mid2_reg_424 );

    SC_METHOD(thread_tmp_i_i_mid2_cast_fu_324_p1);
    sensitive << ( tmp_i_i_mid2_v_reg_417 );

    SC_METHOD(thread_tmp_i_i_mid2_v_fu_250_p3);
    sensitive << ( Col_assign_2_phi_fu_126_p4 );
    sensitive << ( exitcond_flatten_fu_196_p2 );
    sensitive << ( k_fu_190_p2 );

    SC_METHOD(thread_tmp_mid1_13_fu_230_p2);
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_190_p2 );

    SC_METHOD(thread_tmp_mid1_fu_210_p2);
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_190_p2 );

    SC_METHOD(thread_tmp_mid2_14_fu_242_p3);
    sensitive << ( exitcond_flatten_fu_196_p2 );
    sensitive << ( tmp_mid1_13_fu_230_p2 );
    sensitive << ( tmp_2_fu_236_p2 );

    SC_METHOD(thread_tmp_mid2_fu_222_p3);
    sensitive << ( exitcond_flatten_fu_196_p2 );
    sensitive << ( tmp_mid1_fu_210_p2 );
    sensitive << ( tmp3_fu_216_p2 );

    SC_METHOD(thread_tmp_s_fu_327_p3);
    sensitive << ( tmp_i_i_mid2_v_reg_417 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten1_fu_178_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppiten_pp0_it11 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_multiply_top_matrix_multiply_alt2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, indvar_flatten1_reg_111, "indvar_flatten1_reg_111");
    sc_trace(mVcdFile, Col_assign_2_reg_122, "Col_assign_2_reg_122");
    sc_trace(mVcdFile, indvar_flatten_reg_133, "indvar_flatten_reg_133");
    sc_trace(mVcdFile, Row_assign_reg_144, "Row_assign_reg_144");
    sc_trace(mVcdFile, Col_assign_reg_155, "Col_assign_reg_155");
    sc_trace(mVcdFile, exitcond_flatten1_fu_178_p2, "exitcond_flatten1_fu_178_p2");
    sc_trace(mVcdFile, exitcond_flatten1_reg_400, "exitcond_flatten1_reg_400");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_61, "ap_sig_61");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter1, "ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter2, "ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter3, "ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter4, "ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter4");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_184_p2, "indvar_flatten_next1_fu_184_p2");
    sc_trace(mVcdFile, tmp_mid2_fu_222_p3, "tmp_mid2_fu_222_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_409, "tmp_mid2_reg_409");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter1, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter2, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter3, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter4, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter5, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter6, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter7, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter8, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10, "ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10");
    sc_trace(mVcdFile, tmp_mid2_14_fu_242_p3, "tmp_mid2_14_fu_242_p3");
    sc_trace(mVcdFile, tmp_mid2_14_reg_413, "tmp_mid2_14_reg_413");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter1, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter2, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter3, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter4, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter5, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter6, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter7, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter8, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10, "ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_fu_250_p3, "tmp_i_i_mid2_v_fu_250_p3");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_reg_417, "tmp_i_i_mid2_v_reg_417");
    sc_trace(mVcdFile, Col_assign_mid2_fu_288_p3, "Col_assign_mid2_fu_288_p3");
    sc_trace(mVcdFile, Col_assign_mid2_reg_424, "Col_assign_mid2_reg_424");
    sc_trace(mVcdFile, tmp_1_mid2_fu_296_p3, "tmp_1_mid2_fu_296_p3");
    sc_trace(mVcdFile, tmp_1_mid2_reg_429, "tmp_1_mid2_reg_429");
    sc_trace(mVcdFile, c_fu_304_p2, "c_fu_304_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_316_p3, "indvar_flatten_next_fu_316_p3");
    sc_trace(mVcdFile, tmp_17_fu_389_p2, "tmp_17_fu_389_p2");
    sc_trace(mVcdFile, tmp_17_reg_456, "tmp_17_reg_456");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_17_reg_456_pp0_iter2, "ap_reg_ppstg_tmp_17_reg_456_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_17_reg_456_pp0_iter3, "ap_reg_ppstg_tmp_17_reg_456_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_17_reg_456_pp0_iter4, "ap_reg_ppstg_tmp_17_reg_456_pp0_iter4");
    sc_trace(mVcdFile, C_addr_reg_471, "C_addr_reg_471");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_471_pp0_iter6, "ap_reg_ppstg_C_addr_reg_471_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_471_pp0_iter7, "ap_reg_ppstg_C_addr_reg_471_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_471_pp0_iter8, "ap_reg_ppstg_C_addr_reg_471_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_471_pp0_iter9, "ap_reg_ppstg_C_addr_reg_471_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_471_pp0_iter10, "ap_reg_ppstg_C_addr_reg_471_pp0_iter10");
    sc_trace(mVcdFile, sum_mult_addr_reg_476, "sum_mult_addr_reg_476");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter6, "ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter7, "ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter8, "ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter9, "ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter9");
    sc_trace(mVcdFile, grp_fu_172_p2, "grp_fu_172_p2");
    sc_trace(mVcdFile, mult_reg_482, "mult_reg_482");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_482_pp0_iter6, "ap_reg_ppstg_mult_reg_482_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_482_pp0_iter7, "ap_reg_ppstg_mult_reg_482_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_482_pp0_iter8, "ap_reg_ppstg_mult_reg_482_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_482_pp0_iter9, "ap_reg_ppstg_mult_reg_482_pp0_iter9");
    sc_trace(mVcdFile, sum_mult_q0, "sum_mult_q0");
    sc_trace(mVcdFile, grp_fu_166_p2, "grp_fu_166_p2");
    sc_trace(mVcdFile, tmp_4_reg_493, "tmp_4_reg_493");
    sc_trace(mVcdFile, sum_mult_address0, "sum_mult_address0");
    sc_trace(mVcdFile, sum_mult_ce0, "sum_mult_ce0");
    sc_trace(mVcdFile, sum_mult_ce1, "sum_mult_ce1");
    sc_trace(mVcdFile, sum_mult_we1, "sum_mult_we1");
    sc_trace(mVcdFile, sum_mult_d1, "sum_mult_d1");
    sc_trace(mVcdFile, Col_assign_2_phi_fu_126_p4, "Col_assign_2_phi_fu_126_p4");
    sc_trace(mVcdFile, Row_assign_phi_fu_148_p4, "Row_assign_phi_fu_148_p4");
    sc_trace(mVcdFile, tmp_22_cast_fu_370_p1, "tmp_22_cast_fu_370_p1");
    sc_trace(mVcdFile, tmp_23_cast_fu_384_p1, "tmp_23_cast_fu_384_p1");
    sc_trace(mVcdFile, tmp_24_cast_fu_395_p1, "tmp_24_cast_fu_395_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_196_p2, "exitcond_flatten_fu_196_p2");
    sc_trace(mVcdFile, k_fu_190_p2, "k_fu_190_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_210_p2, "tmp_mid1_fu_210_p2");
    sc_trace(mVcdFile, tmp3_fu_216_p2, "tmp3_fu_216_p2");
    sc_trace(mVcdFile, tmp_mid1_13_fu_230_p2, "tmp_mid1_13_fu_230_p2");
    sc_trace(mVcdFile, tmp_2_fu_236_p2, "tmp_2_fu_236_p2");
    sc_trace(mVcdFile, exitcond_fu_264_p2, "exitcond_fu_264_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_258_p2, "not_exitcond_flatten_fu_258_p2");
    sc_trace(mVcdFile, Row_assign_mid_fu_202_p3, "Row_assign_mid_fu_202_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_270_p2, "exitcond_mid_fu_270_p2");
    sc_trace(mVcdFile, tmp_13_fu_282_p2, "tmp_13_fu_282_p2");
    sc_trace(mVcdFile, r_fu_276_p2, "r_fu_276_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_310_p2, "indvar_flatten_op_fu_310_p2");
    sc_trace(mVcdFile, tmp_s_fu_327_p3, "tmp_s_fu_327_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_334_p1, "p_shl1_cast_fu_334_p1");
    sc_trace(mVcdFile, tmp_i_i_mid2_cast_fu_324_p1, "tmp_i_i_mid2_cast_fu_324_p1");
    sc_trace(mVcdFile, tmp_fu_347_p3, "tmp_fu_347_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_354_p1, "p_shl_cast_fu_354_p1");
    sc_trace(mVcdFile, tmp_1_mid2_cast_fu_344_p1, "tmp_1_mid2_cast_fu_344_p1");
    sc_trace(mVcdFile, tmp_14_fu_358_p2, "tmp_14_fu_358_p2");
    sc_trace(mVcdFile, tmp_15_fu_364_p2, "tmp_15_fu_364_p2");
    sc_trace(mVcdFile, tmp_i_i4_cast_fu_375_p1, "tmp_i_i4_cast_fu_375_p1");
    sc_trace(mVcdFile, tmp_12_fu_338_p2, "tmp_12_fu_338_p2");
    sc_trace(mVcdFile, tmp_16_fu_378_p2, "tmp_16_fu_378_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_2, "ap_sig_cseq_ST_st14_fsm_2");
    sc_trace(mVcdFile, ap_sig_395, "ap_sig_395");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_229, "ap_sig_229");
#endif

    }
}

matrix_multiply_top_matrix_multiply_alt2::~matrix_multiply_top_matrix_multiply_alt2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_mult_U;
    delete matrix_multiply_top_fadd_32ns_32ns_32_5_full_dsp_U0;
    delete matrix_multiply_top_fmul_32ns_32ns_32_4_max_dsp_U1;
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_400.read(), ap_const_lv1_0))) {
        Col_assign_2_reg_122 = tmp_i_i_mid2_v_reg_417.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_2_reg_122 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
        Col_assign_reg_155 = c_fu_304_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_reg_155 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_400.read(), ap_const_lv1_0))) {
        Row_assign_reg_144 = tmp_1_mid2_reg_429.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Row_assign_reg_144 = ap_const_lv2_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
        indvar_flatten1_reg_111 = indvar_flatten_next1_fu_184_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten1_reg_111 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_133 = indvar_flatten_next_fu_316_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_133 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter4.read(), ap_const_lv1_0)) {
        C_addr_reg_471 =  (sc_lv<4>) (tmp_24_cast_fu_395_p1.read());
        mult_reg_482 = grp_fu_172_p2.read();
        sum_mult_addr_reg_476 =  (sc_lv<4>) (tmp_24_cast_fu_395_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
        Col_assign_mid2_reg_424 = Col_assign_mid2_fu_288_p3.read();
        tmp_mid2_14_reg_413 = tmp_mid2_14_fu_242_p3.read();
        tmp_mid2_reg_409 = tmp_mid2_fu_222_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_C_addr_reg_471_pp0_iter10 = ap_reg_ppstg_C_addr_reg_471_pp0_iter9.read();
        ap_reg_ppstg_C_addr_reg_471_pp0_iter6 = C_addr_reg_471.read();
        ap_reg_ppstg_C_addr_reg_471_pp0_iter7 = ap_reg_ppstg_C_addr_reg_471_pp0_iter6.read();
        ap_reg_ppstg_C_addr_reg_471_pp0_iter8 = ap_reg_ppstg_C_addr_reg_471_pp0_iter7.read();
        ap_reg_ppstg_C_addr_reg_471_pp0_iter9 = ap_reg_ppstg_C_addr_reg_471_pp0_iter8.read();
        ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter2 = ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter1.read();
        ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter3 = ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter2.read();
        ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter4 = ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter3.read();
        ap_reg_ppstg_mult_reg_482_pp0_iter6 = mult_reg_482.read();
        ap_reg_ppstg_mult_reg_482_pp0_iter7 = ap_reg_ppstg_mult_reg_482_pp0_iter6.read();
        ap_reg_ppstg_mult_reg_482_pp0_iter8 = ap_reg_ppstg_mult_reg_482_pp0_iter7.read();
        ap_reg_ppstg_mult_reg_482_pp0_iter9 = ap_reg_ppstg_mult_reg_482_pp0_iter8.read();
        ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter6 = sum_mult_addr_reg_476.read();
        ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter7 = ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter6.read();
        ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter8 = ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter7.read();
        ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter9 = ap_reg_ppstg_sum_mult_addr_reg_476_pp0_iter8.read();
        ap_reg_ppstg_tmp_17_reg_456_pp0_iter2 = tmp_17_reg_456.read();
        ap_reg_ppstg_tmp_17_reg_456_pp0_iter3 = ap_reg_ppstg_tmp_17_reg_456_pp0_iter2.read();
        ap_reg_ppstg_tmp_17_reg_456_pp0_iter4 = ap_reg_ppstg_tmp_17_reg_456_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter2 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter3 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter4 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter5 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter6 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter7 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter8 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9 = ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter8.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter2 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter3 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter4 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter5 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter6 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter7 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter8 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9 = ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter8.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_exitcond_flatten1_reg_400_pp0_iter1 = exitcond_flatten1_reg_400.read();
        ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter1 = tmp_mid2_14_reg_413.read();
        ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter1 = tmp_mid2_reg_409.read();
        exitcond_flatten1_reg_400 = exitcond_flatten1_fu_178_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten1_reg_400.read(), ap_const_lv1_0))) {
        tmp_17_reg_456 = tmp_17_fu_389_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0))) {
        tmp_1_mid2_reg_429 = tmp_1_mid2_fu_296_p3.read();
        tmp_i_i_mid2_v_reg_417 = tmp_i_i_mid2_v_fu_250_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read())) {
        tmp_4_reg_493 = grp_fu_166_p2.read();
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_A_address0() {
    A_address0 =  (sc_lv<4>) (tmp_22_cast_fu_370_p1.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_B_address0() {
    B_address0 =  (sc_lv<4>) (tmp_23_cast_fu_384_p1.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_C_address0() {
    C_address0 = ap_reg_ppstg_C_addr_reg_471_pp0_iter10.read();
}

void matrix_multiply_top_matrix_multiply_alt2::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read())) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_C_d0() {
    C_d0 = tmp_4_reg_493.read();
}

void matrix_multiply_top_matrix_multiply_alt2::thread_C_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter10.read())))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_Col_assign_2_phi_fu_126_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_400.read(), ap_const_lv1_0))) {
        Col_assign_2_phi_fu_126_p4 = tmp_i_i_mid2_v_reg_417.read();
    } else {
        Col_assign_2_phi_fu_126_p4 = Col_assign_2_reg_122.read();
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_Col_assign_mid2_fu_288_p3() {
    Col_assign_mid2_fu_288_p3 = (!tmp_13_fu_282_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_13_fu_282_p2.read()[0].to_bool())? ap_const_lv2_0: Col_assign_reg_155.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_Row_assign_mid_fu_202_p3() {
    Row_assign_mid_fu_202_p3 = (!exitcond_flatten_fu_196_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten_fu_196_p2.read()[0].to_bool())? ap_const_lv2_0: Row_assign_phi_fu_148_p4.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_Row_assign_phi_fu_148_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_400.read(), ap_const_lv1_0))) {
        Row_assign_phi_fu_148_p4 = tmp_1_mid2_reg_429.read();
    } else {
        Row_assign_phi_fu_148_p4 = Row_assign_reg_144.read();
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_229() {
    ap_sig_229 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_395() {
    ap_sig_395 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_61() {
    ap_sig_61 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_61.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st14_fsm_2() {
    if (ap_sig_395.read()) {
        ap_sig_cseq_ST_st14_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_2 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_c_fu_304_p2() {
    c_fu_304_p2 = (!Col_assign_mid2_fu_288_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Col_assign_mid2_fu_288_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_exitcond_flatten1_fu_178_p2() {
    exitcond_flatten1_fu_178_p2 = (!indvar_flatten1_reg_111.read().is_01() || !ap_const_lv5_1B.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten1_reg_111.read() == ap_const_lv5_1B);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_exitcond_flatten_fu_196_p2() {
    exitcond_flatten_fu_196_p2 = (!indvar_flatten_reg_133.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_133.read() == ap_const_lv4_9);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_exitcond_fu_264_p2() {
    exitcond_fu_264_p2 = (!Col_assign_reg_155.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_155.read() == ap_const_lv2_3);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_exitcond_mid_fu_270_p2() {
    exitcond_mid_fu_270_p2 = (exitcond_fu_264_p2.read() & not_exitcond_flatten_fu_258_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_indvar_flatten_next1_fu_184_p2() {
    indvar_flatten_next1_fu_184_p2 = (!indvar_flatten1_reg_111.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten1_reg_111.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_indvar_flatten_next_fu_316_p3() {
    indvar_flatten_next_fu_316_p3 = (!exitcond_flatten_fu_196_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_fu_196_p2.read()[0].to_bool())? ap_const_lv4_1: indvar_flatten_op_fu_310_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_indvar_flatten_op_fu_310_p2() {
    indvar_flatten_op_fu_310_p2 = (!indvar_flatten_reg_133.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_133.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_k_fu_190_p2() {
    k_fu_190_p2 = (!Col_assign_2_phi_fu_126_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Col_assign_2_phi_fu_126_p4.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_not_exitcond_flatten_fu_258_p2() {
    not_exitcond_flatten_fu_258_p2 = (exitcond_flatten_fu_196_p2.read() ^ ap_const_lv1_1);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_p_shl1_cast_fu_334_p1() {
    p_shl1_cast_fu_334_p1 = esl_zext<5,4>(tmp_s_fu_327_p3.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_p_shl_cast_fu_354_p1() {
    p_shl_cast_fu_354_p1 = esl_zext<5,4>(tmp_fu_347_p3.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_r_fu_276_p2() {
    r_fu_276_p2 = (!Row_assign_mid_fu_202_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Row_assign_mid_fu_202_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_sum_mult_address0() {
    sum_mult_address0 =  (sc_lv<4>) (tmp_24_cast_fu_395_p1.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_sum_mult_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read())) {
        sum_mult_ce0 = ap_const_logic_1;
    } else {
        sum_mult_ce0 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_sum_mult_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read())))) {
        sum_mult_ce1 = ap_const_logic_1;
    } else {
        sum_mult_ce1 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_sum_mult_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read())) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read())) {
            sum_mult_d1 = ap_reg_ppstg_mult_reg_482_pp0_iter9.read();
        } else if (ap_sig_229.read()) {
            sum_mult_d1 = grp_fu_166_p2.read();
        } else {
            sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_sum_mult_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_14_reg_413_pp0_iter9.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_409_pp0_iter9.read())))) {
        sum_mult_we1 = ap_const_logic_1;
    } else {
        sum_mult_we1 = ap_const_logic_0;
    }
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp3_fu_216_p2() {
    tmp3_fu_216_p2 = (!Col_assign_2_phi_fu_126_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_2_phi_fu_126_p4.read() == ap_const_lv2_0);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_12_fu_338_p2() {
    tmp_12_fu_338_p2 = (!p_shl1_cast_fu_334_p1.read().is_01() || !tmp_i_i_mid2_cast_fu_324_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl1_cast_fu_334_p1.read()) - sc_biguint<5>(tmp_i_i_mid2_cast_fu_324_p1.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_13_fu_282_p2() {
    tmp_13_fu_282_p2 = (exitcond_mid_fu_270_p2.read() | exitcond_flatten_fu_196_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_14_fu_358_p2() {
    tmp_14_fu_358_p2 = (!p_shl_cast_fu_354_p1.read().is_01() || !tmp_1_mid2_cast_fu_344_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl_cast_fu_354_p1.read()) - sc_biguint<5>(tmp_1_mid2_cast_fu_344_p1.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_15_fu_364_p2() {
    tmp_15_fu_364_p2 = (!tmp_i_i_mid2_cast_fu_324_p1.read().is_01() || !tmp_14_fu_358_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i_mid2_cast_fu_324_p1.read()) + sc_biguint<5>(tmp_14_fu_358_p2.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_16_fu_378_p2() {
    tmp_16_fu_378_p2 = (!tmp_i_i4_cast_fu_375_p1.read().is_01() || !tmp_12_fu_338_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i4_cast_fu_375_p1.read()) + sc_biguint<5>(tmp_12_fu_338_p2.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_17_fu_389_p2() {
    tmp_17_fu_389_p2 = (!tmp_i_i4_cast_fu_375_p1.read().is_01() || !tmp_14_fu_358_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_i_i4_cast_fu_375_p1.read()) + sc_biguint<5>(tmp_14_fu_358_p2.read()));
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_1_mid2_cast_fu_344_p1() {
    tmp_1_mid2_cast_fu_344_p1 = esl_zext<5,2>(tmp_1_mid2_reg_429.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_1_mid2_fu_296_p3() {
    tmp_1_mid2_fu_296_p3 = (!exitcond_mid_fu_270_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_mid_fu_270_p2.read()[0].to_bool())? r_fu_276_p2.read(): Row_assign_mid_fu_202_p3.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_22_cast_fu_370_p1() {
    tmp_22_cast_fu_370_p1 = esl_zext<64,5>(tmp_15_fu_364_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_23_cast_fu_384_p1() {
    tmp_23_cast_fu_384_p1 = esl_sext<64,5>(tmp_16_fu_378_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_24_cast_fu_395_p1() {
    tmp_24_cast_fu_395_p1 = esl_zext<64,5>(ap_reg_ppstg_tmp_17_reg_456_pp0_iter4.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_2_fu_236_p2() {
    tmp_2_fu_236_p2 = (!Col_assign_2_phi_fu_126_p4.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_2_phi_fu_126_p4.read() == ap_const_lv2_2);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_fu_347_p3() {
    tmp_fu_347_p3 = esl_concat<2,2>(tmp_1_mid2_reg_429.read(), ap_const_lv2_0);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_i_i4_cast_fu_375_p1() {
    tmp_i_i4_cast_fu_375_p1 = esl_zext<5,2>(Col_assign_mid2_reg_424.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_i_i_mid2_cast_fu_324_p1() {
    tmp_i_i_mid2_cast_fu_324_p1 = esl_zext<5,2>(tmp_i_i_mid2_v_reg_417.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_i_i_mid2_v_fu_250_p3() {
    tmp_i_i_mid2_v_fu_250_p3 = (!exitcond_flatten_fu_196_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten_fu_196_p2.read()[0].to_bool())? k_fu_190_p2.read(): Col_assign_2_phi_fu_126_p4.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_mid1_13_fu_230_p2() {
    tmp_mid1_13_fu_230_p2 = (!k_fu_190_p2.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_190_p2.read() == ap_const_lv2_2);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_mid1_fu_210_p2() {
    tmp_mid1_fu_210_p2 = (!k_fu_190_p2.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_190_p2.read() == ap_const_lv2_0);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_mid2_14_fu_242_p3() {
    tmp_mid2_14_fu_242_p3 = (!exitcond_flatten_fu_196_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_196_p2.read()[0].to_bool())? tmp_mid1_13_fu_230_p2.read(): tmp_2_fu_236_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_mid2_fu_222_p3() {
    tmp_mid2_fu_222_p3 = (!exitcond_flatten_fu_196_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_196_p2.read()[0].to_bool())? tmp_mid1_fu_210_p2.read(): tmp3_fu_216_p2.read());
}

void matrix_multiply_top_matrix_multiply_alt2::thread_tmp_s_fu_327_p3() {
    tmp_s_fu_327_p3 = esl_concat<2,2>(tmp_i_i_mid2_v_reg_417.read(), ap_const_lv2_0);
}

void matrix_multiply_top_matrix_multiply_alt2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten1_fu_178_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st14_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

