// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_multiply_top_HH_
#define _matrix_multiply_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matrix_multiply_top_matrix_multiply_alt2.h"
#include "matrix_multiply_top_a_i.h"

namespace ap_rtl {

struct matrix_multiply_top : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > A_address0;
    sc_out< sc_logic > A_ce0;
    sc_in< sc_lv<32> > A_q0;
    sc_out< sc_lv<4> > B_address0;
    sc_out< sc_logic > B_ce0;
    sc_in< sc_lv<32> > B_q0;
    sc_out< sc_lv<4> > C_address0;
    sc_out< sc_logic > C_ce0;
    sc_out< sc_logic > C_we0;
    sc_out< sc_lv<32> > C_d0;


    // Module declarations
    matrix_multiply_top(sc_module_name name);
    SC_HAS_PROCESS(matrix_multiply_top);

    ~matrix_multiply_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    matrix_multiply_top_a_i* a_i_U;
    matrix_multiply_top_a_i* b_i_U;
    matrix_multiply_top_a_i* C_assign_U;
    matrix_multiply_top_matrix_multiply_alt2* grp_matrix_multiply_top_matrix_multiply_alt2_fu_198;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_26;
    sc_signal< sc_lv<2> > r_1_fu_211_p2;
    sc_signal< sc_lv<2> > r_1_reg_388;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_59;
    sc_signal< sc_lv<5> > tmp_9_fu_233_p2;
    sc_signal< sc_lv<5> > tmp_9_reg_393;
    sc_signal< sc_lv<1> > exitcond5_fu_205_p2;
    sc_signal< sc_lv<2> > c_1_fu_245_p2;
    sc_signal< sc_lv<2> > c_1_reg_401;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_74;
    sc_signal< sc_lv<64> > tmp_12_cast_fu_260_p1;
    sc_signal< sc_lv<64> > tmp_12_cast_reg_406;
    sc_signal< sc_lv<1> > exitcond4_fu_239_p2;
    sc_signal< sc_lv<2> > r_2_fu_271_p2;
    sc_signal< sc_lv<2> > r_2_reg_419;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_90;
    sc_signal< sc_lv<5> > tmp_1_fu_293_p2;
    sc_signal< sc_lv<5> > tmp_1_reg_424;
    sc_signal< sc_lv<1> > exitcond3_fu_265_p2;
    sc_signal< sc_lv<2> > c_2_fu_305_p2;
    sc_signal< sc_lv<2> > c_2_reg_432;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_104;
    sc_signal< sc_lv<64> > tmp_15_cast_fu_320_p1;
    sc_signal< sc_lv<64> > tmp_15_cast_reg_437;
    sc_signal< sc_lv<1> > exitcond2_fu_299_p2;
    sc_signal< sc_lv<2> > r_3_fu_331_p2;
    sc_signal< sc_lv<2> > r_3_reg_450;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_120;
    sc_signal< sc_lv<5> > tmp_7_fu_353_p2;
    sc_signal< sc_lv<5> > tmp_7_reg_455;
    sc_signal< sc_lv<1> > exitcond1_fu_325_p2;
    sc_signal< sc_lv<2> > c_3_fu_365_p2;
    sc_signal< sc_lv<2> > c_3_reg_463;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_134;
    sc_signal< sc_lv<64> > tmp_16_cast_fu_380_p1;
    sc_signal< sc_lv<64> > tmp_16_cast_reg_468;
    sc_signal< sc_lv<1> > exitcond_fu_359_p2;
    sc_signal< sc_lv<4> > a_i_address0;
    sc_signal< sc_logic > a_i_ce0;
    sc_signal< sc_logic > a_i_we0;
    sc_signal< sc_lv<32> > a_i_q0;
    sc_signal< sc_lv<4> > b_i_address0;
    sc_signal< sc_logic > b_i_ce0;
    sc_signal< sc_logic > b_i_we0;
    sc_signal< sc_lv<32> > b_i_q0;
    sc_signal< sc_lv<4> > C_assign_address0;
    sc_signal< sc_logic > C_assign_ce0;
    sc_signal< sc_lv<32> > C_assign_q0;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_done;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_idle;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_ready;
    sc_signal< sc_lv<4> > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_address0;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_A_ce0;
    sc_signal< sc_lv<4> > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_address0;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_B_ce0;
    sc_signal< sc_lv<4> > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_address0;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_ce0;
    sc_signal< sc_logic > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_we0;
    sc_signal< sc_lv<32> > grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_C_d0;
    sc_signal< sc_lv<2> > r_reg_132;
    sc_signal< sc_lv<2> > c_reg_143;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_202;
    sc_signal< sc_lv<2> > r1_reg_154;
    sc_signal< sc_lv<2> > c2_reg_165;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_217;
    sc_signal< sc_lv<2> > r3_reg_176;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_226;
    sc_signal< sc_lv<2> > c4_reg_187;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_240;
    sc_signal< sc_logic > ap_reg_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start;
    sc_signal< sc_lv<4> > tmp_6_fu_221_p3;
    sc_signal< sc_lv<5> > p_shl_cast_fu_229_p1;
    sc_signal< sc_lv<5> > tmp_cast_fu_217_p1;
    sc_signal< sc_lv<5> > tmp_3_cast_fu_251_p1;
    sc_signal< sc_lv<5> > tmp_3_fu_255_p2;
    sc_signal< sc_lv<4> > tmp_s_fu_281_p3;
    sc_signal< sc_lv<5> > p_shl1_cast_fu_289_p1;
    sc_signal< sc_lv<5> > tmp_1_cast_fu_277_p1;
    sc_signal< sc_lv<5> > tmp_7_cast_fu_311_p1;
    sc_signal< sc_lv<5> > tmp_10_fu_315_p2;
    sc_signal< sc_lv<4> > tmp_5_fu_341_p3;
    sc_signal< sc_lv<5> > p_shl2_cast_fu_349_p1;
    sc_signal< sc_lv<5> > tmp_5_cast_fu_337_p1;
    sc_signal< sc_lv<5> > tmp_cast_10_fu_371_p1;
    sc_signal< sc_lv<5> > tmp_11_fu_375_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_st1_fsm_0;
    static const sc_lv<11> ap_ST_st2_fsm_1;
    static const sc_lv<11> ap_ST_st3_fsm_2;
    static const sc_lv<11> ap_ST_st4_fsm_3;
    static const sc_lv<11> ap_ST_st5_fsm_4;
    static const sc_lv<11> ap_ST_st6_fsm_5;
    static const sc_lv<11> ap_ST_st7_fsm_6;
    static const sc_lv<11> ap_ST_st8_fsm_7;
    static const sc_lv<11> ap_ST_st9_fsm_8;
    static const sc_lv<11> ap_ST_st10_fsm_9;
    static const sc_lv<11> ap_ST_st11_fsm_10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_A_address0();
    void thread_A_ce0();
    void thread_B_address0();
    void thread_B_ce0();
    void thread_C_address0();
    void thread_C_assign_address0();
    void thread_C_assign_ce0();
    void thread_C_ce0();
    void thread_C_d0();
    void thread_C_we0();
    void thread_a_i_address0();
    void thread_a_i_ce0();
    void thread_a_i_we0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_104();
    void thread_ap_sig_120();
    void thread_ap_sig_134();
    void thread_ap_sig_202();
    void thread_ap_sig_217();
    void thread_ap_sig_226();
    void thread_ap_sig_240();
    void thread_ap_sig_26();
    void thread_ap_sig_59();
    void thread_ap_sig_74();
    void thread_ap_sig_90();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_b_i_address0();
    void thread_b_i_ce0();
    void thread_b_i_we0();
    void thread_c_1_fu_245_p2();
    void thread_c_2_fu_305_p2();
    void thread_c_3_fu_365_p2();
    void thread_exitcond1_fu_325_p2();
    void thread_exitcond2_fu_299_p2();
    void thread_exitcond3_fu_265_p2();
    void thread_exitcond4_fu_239_p2();
    void thread_exitcond5_fu_205_p2();
    void thread_exitcond_fu_359_p2();
    void thread_grp_matrix_multiply_top_matrix_multiply_alt2_fu_198_ap_start();
    void thread_p_shl1_cast_fu_289_p1();
    void thread_p_shl2_cast_fu_349_p1();
    void thread_p_shl_cast_fu_229_p1();
    void thread_r_1_fu_211_p2();
    void thread_r_2_fu_271_p2();
    void thread_r_3_fu_331_p2();
    void thread_tmp_10_fu_315_p2();
    void thread_tmp_11_fu_375_p2();
    void thread_tmp_12_cast_fu_260_p1();
    void thread_tmp_15_cast_fu_320_p1();
    void thread_tmp_16_cast_fu_380_p1();
    void thread_tmp_1_cast_fu_277_p1();
    void thread_tmp_1_fu_293_p2();
    void thread_tmp_3_cast_fu_251_p1();
    void thread_tmp_3_fu_255_p2();
    void thread_tmp_5_cast_fu_337_p1();
    void thread_tmp_5_fu_341_p3();
    void thread_tmp_6_fu_221_p3();
    void thread_tmp_7_cast_fu_311_p1();
    void thread_tmp_7_fu_353_p2();
    void thread_tmp_9_fu_233_p2();
    void thread_tmp_cast_10_fu_371_p1();
    void thread_tmp_cast_fu_217_p1();
    void thread_tmp_s_fu_281_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
